### ISSUE TITLE
✨ Implement export `.csv` as `mgm-hurry` feature

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/MoniGoMani#101]
Implement @raftersvk's [`Export-MGM-result.py`](https://github.com/Rikj000/MoniGoMani/files/6851735/Export-MGM-result.py.log) so it automatically outputs a `.csv` file (With all the proper parameters of a HO result) together with the current automated `.log` file export.

How it should be implemented:
- A new command called `mgm-hurry export_csv`
- Store the `.csv` file in the `hyperopt_results` folder (following the naming scheme/logic of the other automated result exports `HyperOptResults-<output_file_name>.csv`)
- Which should also be executable through a new `--export_csv` modifier for the `mgm-hurry hyperopt` command (`True` by default)

**Comment by raftersvk** [comment]
here is a start :
https://github.com/raftersvk/MoniGoMani_raftersvk/pull/6

**Comment by raftersvk** [comment]
next step is to export "detailed signal" result with each signal percentage weight of each epoch

**Comment by Rikj000** [comment]
> here is a start :
> [raftersvk#6](https://github.com/raftersvk/MoniGoMani_raftersvk/pull/6)

Nice, please open it up as a PR to the official repo :slightly_smiling_face:
I won't merge new stuff before issue #100 is solved though

**Comment by Rikj000** [comment]
Implemented as `mgm-hurry export_csv` in commit [`708cdbf`](https://github.com/Rikj000/MoniGoMani/commit/708cdbf1743d2efa5f494b621b6e5f6fa60125b2)! :tada:
