### ISSUE TITLE
⚡️ Add feature to install `FreqUI` using `mgm-hurry`

### ISSUE THREAD

**Issue by topscoder** [Rikj000/MoniGoMani#102]
Installing `frequi` is one of the functions `mgm-hurry` currently doesn't have, but could be useful because `mgm-hurry` will remain the _one-stop-shop_.

More info about `frequi` at https://www.freqtrade.io/en/stable/rest-api/#frequi

**Comment by Rikj000** [comment]
> Installing `frequi` is one of the functions `mgm-hurry` currently doesn't have, but could be useful because `mgm-hurry` will remain the _one-stop-shop_.

Sure, would be a good additional question to ask in `mgm-hurry setup` :slightly_smiling_face:

**Comment by Rikj000** [comment]
Implemented with latest code push: https://github.com/Rikj000/MoniGoMani/compare/af1915a9396e...71470c3ac1dd
