### ISSUE TITLE
Resize the entire MGM repository in order to remove the need to download unneccesary (big) files

### ISSUE THREAD

**Issue by topscoder** [Rikj000/MoniGoMani#104]
Currently checking out the MGM repo takes some time and disk-space because the entire repo is 264.41Mb big. That's quite big for a Python (strategy) tool.

It is probably a good idea to rethink the repo structure and find new locations for eg. the result-files.

**Comment by Rikj000** [comment]
I don't plan on hosting a FTP server for these files & wish to keep using the ease of `git` & Github for storing the test results.
However I will scrub the [`MoniGoManiHyperStrategy_v0.9.0_nightshift2ks_ClusterResults_22-04-2021.zip`](https://github.com/Rikj000/MoniGoMani/blob/main/Some%20Test%20Results/v0.9.0/MoniGoManiHyperStrategy_v0.9.0_nightshift2ks_ClusterResults_22-04-2021.zip) which will decrease the [`Some Test Results `](https://github.com/Rikj000/MoniGoMani/tree/development/Some%20Test%20Results) folder in size by 75%

**Comment by Rikj000** [comment]
[`MFI - plotprofit-results.zip`](https://github.com/Rikj000/MoniGoMani/blob/development/Some%20Test%20Results/v0.12.0/MFI/backtest%20and%20plot%20results/plotprofit-results.zip) will also be scrubbed.

Size before deletion of `.zip`'s: 110Mb
Size after deletion of `.zip`'s: 23Mb

**Comment by topscoder** [comment]
That's a lot! :)

But, these files remain in the repo-history and don't shrink the entire repo size I think?

**Comment by Corfucinas** [comment]
Rebase?
