### ISSUE TITLE
Discuss cleanup strategy files `mgm-hurry cleanup`

### ISSUE THREAD

**Issue by topscoder** [Rikj000/MoniGoMani#107]
This check should not be removed!
Other strategies create a `StrategyName.json` file after HyperOpting and it must be possible to clear these with `mgm-hurry cleanup`

_Originally posted by @Rikj000 in https://github.com/Rikj000/MoniGoMani/pull/106#discussion_r689903419_

**Comment by topscoder** [comment]
Currently this is how `mgm-hurry cleanup` handles cleaning mom ho files:

```python3
    ...
        cleaned_up = False
        if strategy == 'MoniGoManiHyperStrategy':
            # Remove mgm-config-hyperopt file to cleanup
            cleaned_up = self.monigomani_config.cleanup_hyperopt_files()
    ...
```

This removes these files:
- mgm-config-hyperopt.json (applied results file)
- MoniGoManiHyperStrategy.json (intermediate results file)

I've changed the check for cleanup because I assumed these 2 files were only created by MGM Strategy and never by another Strategy.

**Comment by Rikj000** [comment]
> I've changed the check for cleanup because I assumed these 2 files were only created by MGM Strategy and never by another Strategy.

This was indeed the case in the past :)

But Freqtrade changed and now automatically creates a **StrategyName.json** after a HyperOpt ran to completion.
It also does this when you do `hyperopt-show`

**Comment by topscoder** [comment]
Check, will fix it ☑️

**Comment by Rikj000** [comment]
Perhaps worth to mention, MGM's `.json` file should still be moved/renamed to `user_data/mgm-config-hyperopt.json`.

This is because MGM handles `.json` loading in a special way and otherwise Freqtrade will screw up our custom data loading process.
