### ISSUE TITLE
❓ How to install `mgm-hurry` / Installation issues

### ISSUE THREAD

**Issue by anakein** [Rikj000/MoniGoMani#141]
i tried install 9 times diferent SO, manual, automatic, pufff.
great project but dont run. i dont undertand.
I think good document for INSTALL is necesary, and later usage.

good luck

**Comment by Rikj000** [comment]
Yush `mgm-hurry` is a good option. How did you try installing it though?

Here's the documentation for how to do it & how to use it:
https://github.com/Rikj000/MoniGoMani/blob/development/Documentation/Docs-MGM-Hurry.md#installation-instructions

Also please provide your error (stacktrace) if the process described there would fail.
However I do admit that I need to make work of re-writing large sections of the documentation because they are becoming outdated, but the `Docs-MGM-Hurry`section is still quite up-to-date.

**Comment by anakein** [comment]
yes. and starting with: 

/dev/fd/63: 173: [: 0: unexpected operator

-e   🚦  Requirements check
-e   ======================

-e   ✅  Python3 is installed.
-e   ✅  Pip3 is installed.
/dev/fd/63: 203: [: "Ubuntu": unexpected operator

I have installed freqtrade yet in other directory.
and python env deactivate

**Comment by Rikj000** [comment]
> /dev/fd/63: 173: [: 0: unexpected operator

Did you read the note for Ubuntu? You need to reconfigure your shell so it will actually use `bash`
https://unix.stackexchange.com/a/442517

**Comment by anakein** [comment]
this is only first problem.

Successfully installed freqtrade-develop
pip install completed

-------------------------
Please use 'freqtrade new-config -c config.json' to generate a new configuration file.
-------------------------
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade <subcommand>'.
You can see the list of available bot sub-commands by executing 'source .env/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .env/bin/activate; freqtrade --version'.
/bin/sh: 1: source: not found
/bin/sh: 1: freqtrade: not found
INFO - ✔ Successfully installed FreqUI!
✔ Freqtrade setup completed! 
INFO - 🍺 Freqtrade has been installed. You can now proceed to install MoniGoMani. (Hint: mgm-hurry install_mgm)
INFO - 💨 💨 💨
       👉 Install MoniGoMani
       💨 💨 💨
🤷 No "mgm-config.json" file found.
WARNING - 🤷 No "mgm-config.json" file found.
✔ 👉  Clone MoniGoMani repository on the latest commit
⠼ 👉  Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking filesCRITICAL - [('/tmp/tmpy2xk22m4/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.pack', '/home/anakein/Mgm/freqtrade-mgm/monigomani/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.pack', "[Errno 13] Permission denied: '/home/anakein/Mgm/freqtrade-mgm/monigomani/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.pack'"), ('/tmp/tmpy2xk22m4/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.idx', '/home/anakein/Mgm/freqtrade-mgm/monigomani/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.idx', "[Errno 13] Permission denied: '/home/anakein/Mgm/freqtrade-mgm/monigomani/.git/objects/pack/pack-d3410d92f7b583b5667d1933c97495a91d15a8cc.idx'")]
😕 MoniGoMani installation failed

**Comment by Rikj000** [comment]
> /bin/sh: 1: source: not found
> /bin/sh: 1: freqtrade: not found

Please re-configure your shell to use bash as I mentioned in my previous post, this error usually means that didn't happen yet on Ubuntu installations. I assume your OS is Ubuntu, right?

**Comment by nuaimat** [comment]
I also noticed "Permission denied" errors
Please check directory permissions. It should be writable by the current user

It would be easier for us to help if you list your environment setup (OS, version) and the steps you took.

**Comment by anakein** [comment]
i tried, thanks.
because i want to help, i have some ideas, for example, remote and shared hyperopt. 

thanks again.

**Comment by Rikj000** [comment]
> because i want to help, i have some ideas, for example, remote and shared hyperopt.

Remote HO might be implemented in the far future (simply way too much other work left to be done for now).
But atm we need to know your OS to help you out further.

**Comment by anakein** [comment]
im installing again with bash and premissions changed.

im waiting.

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by anakein** [comment]
permision problem. installed but.... jeje 
INFO - Using indicator startup period: 400 ...
INFO - NumExpr defaulting to 6 threads.
INFO - Loading data from 2021-05-30 14:40:00 up to 2021-09-11 00:00:00 (103 days).
INFO - Dataload complete. Calculating indicators
INFO - Hyperopting with data from 2021-06-01 00:00:00 up to 2021-09-11 00:00:00 (102 days)..
INFO - Found 6 CPU cores. Let's make them scream!
INFO - Number of parallel jobs set as: -1
INFO - Effective number of parallel workers used: 6
ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/anakein/Mgm/freqtrade-mgm/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/anakein/Mgm/freqtrade-mgm/freqtrade/commands/optimize_commands.py", line 87, in start_hyperopt
    hyperopt.start()
  File "/home/anakein/Mgm/freqtrade-mgm/freqtrade/optimize/hyperopt.py", line 455, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/anakein/Mgm/freqtrade-mgm/freqtrade/optimize/hyperopt.py", line 368, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/anakein/Mgm/freqtrade-mgm/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/anakein/Mgm/freqtrade-mgm/.env/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/anakein/Mgm/freqtrade-mgm/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

**Comment by Rikj000** [comment]
Hmmm, try with `--jobs=1`.
Also how much RAM has your system?
And please don't do anything else that would take up a lot of system resources when running a HO.

**Comment by anakein** [comment]
I'm making hyperopt in freqtrade standar with 4 processors and 4 gb
last test: 8 processors and 8 gb crash computer.
[capture](https://neta2.com/Captura.PNG)

**Comment by anakein** [comment]
look open process. with --jobs=1
are there too much open process?
[process](https://neta2.com/Captura2.PNG)

**Comment by taina0407** [comment]
> look open process. with --jobs=1
> are there too much open process?
> [process](https://neta2.com/Captura2.PNG)

I think the correct syntax for --jobs is "--jobs 1", could u try

**Comment by Rikj000** [comment]
> I think the correct syntax for --jobs is "--jobs 1", could u try

With `mgm-hurry` you should be able to use either `--jobs=1` or `--jobs 1` :wink: 

@anakein This is very strange though, I've never seen these issues before on an installation :thinking: 
What if you try to HO without `mgm-hurry`? *(So we can better locate where the issue resides)*

Use this command to test: `source ./.env/bin/activate; freqtrade hyperopt`

**Comment by NecroJogn** [comment]
I have also had problems installing MGM on Ubuntu since my last re-install. But I have been half-assing through the process so I always thought I wasn't paying attention to the docs properly (and therefore no questions about it :P ). I am ready to believe there is some kind of problem though. (I have done the bash thing). So I'll make another try tonight or tomorrow and keep notes about the process

**Comment by Rikj000** [comment]
@NecroJogn I recently successfully installed `mgm-hurry` on a Ubuntu WSL though + Others also already successfully installed on their native Ubuntu rigs.

Those where clean installations though because back then the update process wasn't working yet.
Perhaps Ubuntu needs some more specific stuff for updating.

However that does not explain why freqtrade got installed, is running and then crashes at the start of the HO (which @anakein currently is suffering from)

**Comment by anakein** [comment]
ok, i have information yet.
we need 2gb for each job.
with 6gb you need to put --jobs=3
with 8gb you can to put --jobs=4
for older computer or raspberry --jobs=1

**Comment by Rikj000** [comment]
> we need 2gb for each job.

This is incorrect, I often run 12 parallel jobs on a 16Gb machine with only about 8-10Gb of RAM in use.

Things that increase RAM usage:
- More pairs in your static pairlist
- More parallel jobs
- Longer timeranges being HyperOpted

Where the static pairlist will influence the RAM usage the most

**Comment by anakein** [comment]
> 
> 
> > we need 2gb for each job.
> 
> This is incorrect, I often run 12 parallel jobs on a 16Gb machine with only about 8-10Gb of RAM in use.
> 
> Things that increase RAM usage:
> 
>     * More pairs in your static pairlist
> 
>     * More parallel jobs
> 
>     * Longer timeranges being HyperOpted
> 
> 
> Where the static pairlist will influence the RAM usage the most

It is not an exact number, it is an estimate.
in any case it is not a problem yours is a problem of hyperopt of freqtrade.
