### ISSUE TITLE
🐞 `mgm-hurry download_candle_data` not using provided `timerange`

### ISSUE THREAD

**Issue by NecroJogn** [Rikj000/MoniGoMani#147]
There is possibly an unwanted behavior of the `hurry download_candle_data` timerange. 

The error/bug/thing
![image](https://user-images.githubusercontent.com/73529476/134660495-83306adc-e978-4816-8316-25d91e6c5b65.png) 

The .hurry timerange
![image](https://user-images.githubusercontent.com/73529476/134660706-da4b7ebc-de5a-4668-8757-41daaa9abac7.png)

When selecting "Yes" to the last question, it will take the timerange as defined in .hurry to calculate the start date, even though a different timerange was stated in the command.
When selecting "No" this works correctly and it downloads the data in the timerange as defined in the command. 

After some thought, it already states that it will do that, so it is hardly a bug. But maybe not the smoothest way for it to work. Since a timerange was specified just above, I think it should stick to that and add the candle data to that date.

**Comment by NecroJogn** [comment]
I can add that it was not caused by not specifying full timerange 

![image](https://user-images.githubusercontent.com/73529476/134667703-03da5c18-1b3d-4eeb-beaa-cc32ddbf3c79.png)

**Comment by Rikj000** [comment]
Bug fixed with commit https://github.com/Rikj000/MoniGoMani/commit/f416e61fa6bf9ea42bf6a0a555287ad1ec3b7211 :smile:
![mgm_hurry_download_candle_data](https://user-images.githubusercontent.com/24852597/134940388-5aef94ff-1d66-40a4-9228-2853d742ac2e.png)
