### ISSUE TITLE
🔥 Remove broken `docker` support

### ISSUE THREAD

**Issue by agustin9014** [Rikj000/MoniGoMani#148]
Freqtrade-MoniGoMani | 2021-09-30 01:52:50,151 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
Freqtrade-MoniGoMani | 2021-09-30 01:52:50,152 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
Freqtrade-MoniGoMani | 2021-09-30 01:52:50,165 - freqtrade.commands.trade_commands - ERROR - Expecting property name enclosed in double quotes: line 13 column 1 (char 612)
Freqtrade-MoniGoMani | 2021-09-30 01:52:50,165 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Freqtrade-MoniGoMani | Traceback (most recent call last):
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
Freqtrade-MoniGoMani |     worker = Worker(args)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
Freqtrade-MoniGoMani |     self._init(False)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
Freqtrade-MoniGoMani |     self.freqtrade = FreqtradeBot(self._config)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
Freqtrade-MoniGoMani |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
Freqtrade-MoniGoMani |     strategy: IStrategy = StrategyResolver._load_strategy(
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 196, in _load_strategy
Freqtrade-MoniGoMani |     strategy = StrategyResolver._load_object(paths=abs_paths,
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/iresolver.py", line 120, in _load_object
Freqtrade-MoniGoMani |     (module, module_path) = cls._search_object(directory=_path,
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/iresolver.py", line 102, in _search_object
Freqtrade-MoniGoMani |     obj = next(cls._get_valid_object(module_path, object_name), None)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/iresolver.py", line 66, in _get_valid_object
Freqtrade-MoniGoMani |     spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
Freqtrade-MoniGoMani |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
Freqtrade-MoniGoMani |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Freqtrade-MoniGoMani |   File "/freqtrade/user_data/strategies/MasterMoniGoManiHyperStrategy.py", line 30, in <module>
Freqtrade-MoniGoMani |     class MasterMoniGoManiHyperStrategy(IStrategy, ABC):
Freqtrade-MoniGoMani |   File "/freqtrade/user_data/strategies/MasterMoniGoManiHyperStrategy.py", line 134, in MasterMoniGoManiHyperStrategy
Freqtrade-MoniGoMani |     mgm_config_hyperopt = json.load(file_object)
Freqtrade-MoniGoMani |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
Freqtrade-MoniGoMani |     return loads(fp.read(),
Freqtrade-MoniGoMani |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
Freqtrade-MoniGoMani |     return _default_decoder.decode(s)
Freqtrade-MoniGoMani |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
Freqtrade-MoniGoMani |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Freqtrade-MoniGoMani |   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
Freqtrade-MoniGoMani |     obj, end = self.scan_once(s, idx)
Freqtrade-MoniGoMani | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 1 (char 612)

**Comment by Rikj000** [comment]
You appear to be on a too new version of Freqtrade.
Please stick to a `source` install on the `development` branch for now: [Wiki - `development` branch docs](https://github.com/Rikj000/MoniGoMani/wiki#monigomani-development-branch-documentation)
This might get fixed in [Issue 91](https://github.com/Rikj000/MoniGoMani/issues/91), but `docker` might also be scrapped completely temporarily because it's not that easy to keep it at a static Freqtrade version/commit, it neither gives flexibility to choose a version/commit of choice.
I deem the core MGM framework & mgm-hurry itself of more importance then docker at this point in time.

**Comment by Rikj000** [comment]
Decided to scrap `docker` support as a whole, at least for the time being.
At some point I **might** bring it back, but not planning on doing so any time soon.

**Comment by Rikj000** [comment]
Broken `docker` support has been removed: https://github.com/Rikj000/MoniGoMani/commit/8dfa6804709fd608f8c7671d4495f144e1d6d8c5 & https://github.com/Rikj000/MoniGoMani/commit/0a279855c0fde315b7d99b871a050157e2031505
