### ISSUE TITLE
WARNING - Could not import /home/johan/freqtrade/user_data/strategies/MoniGoManiHyperStrategy.py due to 'cannot import name 'CategoricalParameter' from 'freqtrade.strategy' (/home/name/freqtrade/freqtrade/strategy/__init__.py)'

### ISSUE THREAD

**Issue by Jooopiert** [Rikj000/MoniGoMani#18]
Hello, 

I wanted to try this strategy. I followed the instruction manuall and downloaded and copy the files to freqtrade but it came up with an error. Do you know what I need to change to fix this?

Error: WARNING - Could not import /home/johan/freqtrade/user_data/strategies/MoniGoManiHyperStrategy.py due to 'cannot import name 'CategoricalParameter' from 'freqtrade.strategy' (/home/johan/freqtrade/freqtrade/strategy/__init__.py)'

Thanks in advance!

**Comment by Rikj000** [comment]
Closing since answer is in the [VERYQUICKSTART.md](https://github.com/Rikj000/MoniGoMani/blob/main/VERYQUICKSTART.md#very-quick-start-from-source-code)..
