### ISSUE TITLE
Always loosing

### ISSUE THREAD

**Issue by edebie** [Rikj000/MoniGoMani#20]
I'm running the bot with default parameters for one week so far in simulated mode. I'm only loosing all the time. The sell signals are not quite accurate. For example, two days ago the bot bought MATIC/BTC and achieved max 35% profit and did not sell at this point. Rather, it waited and sold when it was 12% only. 

So, my question here is: do we need to optimize the bot before every run? and how?

**Comment by wobrawu** [comment]
> I'm running the bot with default parameters for one week so far in simulated mode. I'm only loosing all the time. The sell signals are not quite accurate. For example, two days ago the bot bought MATIC/BTC and achieved max 35% profit and did not sell at this point. Rather, it waited and sold when it was 12% only.
> 
> So, my question here is: do we need to optimize the bot before every run? and how?

met the some problem.
