### ISSUE TITLE
🐞 BugFix - `mgm-hurry hyperopt --spaces` is not correctly accepting multiple spaces on some OSes

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/MoniGoMani#243]
Currently on some OSes when running for example `mgm-hurry hyperopt --spaces 'buy sell roi'` *(Multiple spaces)*,   
then MGM-Hurry won't parse the spaces correctly anymore & will result in a crash as following:

![spaces-crash](https://media.discordapp.net/attachments/829415367713095710/932722706049282128/4ec1d39b5dfb2ff4351b6da1cc68ea32.png)

## Suggested permanent fix
See comment from @SybrandDoev below: [Link](https://github.com/Rikj000/MoniGoMani/issues/243#issuecomment-1017391623)

## Temporary workarounds
- Don't use `--spaces`! Simply define the spaces you wish to use in `.hurry` for now if you suffer from this bug :slightly_smiling_face: 
- [Switch from `bash` to `fish`](https://discord.com/channels/819237123009150977/831519376783441961/848455724707479602)

**Comment by Rikj000** [comment]
It appears that bash is eating quotes on some OSes :thinking: 
See: [Fire Docs - Argument Parsing](https://google.github.io/python-fire/guide/#argument-parsing)
![fire-docs-argument-parsing](https://media.discordapp.net/attachments/825778792214691840/933107813092307046/unknown.png)

**Comment by Rikj000** [comment]
All of following alternative writing ways have been tested & confirmed working on my end:
```bash
mgm-hurry hyperopt --spaces 'buy sell roi'
mgm-hurry hyperopt --spaces "buy sell roi"
mgm-hurry hyperopt --spaces buy\ sell\ roi
mgm-hurry hyperopt "--spaces buy sell roi"
mgm-hurry hyperopt --spaces '"buy sell roi"'
mgm-hurry hyperopt --spaces "'buy sell roi'"
```
However on the users side that reported these issues, none of these alternative writing ways helped out

**Comment by SybrandDoev** [comment]
This error is caused by the newly added shell alias. The installer.sh adds this alias via:

## Replace `/path/to/installation/Freqtrade-MGM/`
```bash
echo "mgm-hurry() { pushd /path/to/installation/Freqtrade-MGM/ &> /dev/null; python3 -m pipenv run python3 ./mgm-hurry "\$@"; popd &> /dev/null; }" >> ~/.bashrc
```

As you can see, the echo uses two sets of double quotes `"" ""`. That doesn't work.   

It should be either:
```bash
"mgm-hurry .... '\$@' ... }"
```
Or the other way around: `' "" '`   

I changed my alias (with the correct path ofc.) manually to:

```bash
mgm-hurry() { pushd /path/to/installation/Freqtrade-MGM/ &> /dev/null; python3 -m pipenv run python3 ./mgm-hurry "$@"; popd &> /dev/null; } 
```

**And the problem was gone**. no more timeframe sell.

**Discord Reference:** [Link](https://discord.com/channels/819237123009150977/829415367713095710/933671665076949002)

**Comment by Rikj000** [comment]
Should be fixed with commit: https://github.com/Rikj000/MoniGoMani/commit/ce7c127b224dd8ae2f98edaf37dca51889ce0eb0

Please let me know if it's fixed by doing a clean install with new shell aliases!

**But before you test** make sure to remove the previous `mgm-hurry` alias from `~/.bashrc` 
*(You can edit it with `nano` or whatever you prefer, the `mgm-hurry` alias should be at the very end)*
And also remove the `~/.config/fish/functions/mgm-hurry.fish` file if it exits

**Comment by Rikj000** [comment]
Confirmed as fixed by the MGM community! 🎉 

Please manually remove the old shell aliases as described above,   
then do a clean install and let it create you some new, bug-free shell aliases! 🥳
