### ISSUE TITLE
HyperOpt Individual Spaces

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/MoniGoMani#47]
It has been reported that HyperOpting individual spaces doesn't work anymore.   
This still needs to be investigated further though.

**Comment by denvers** [comment]
Confirmed. Only one space fails to print HyperOpting results (which space doesn't make sense).

Although, I found out that it will work if you add `--print-all`.

Eg. `freqtrade hyperopt  **--print-all** -s MoniGoManiHyperStrategy -c ./user_data/mgm-config.json -c ./user_data/mgm-config-private.json --hyperopt-loss WinRatioAndProfitRatioLoss --spaces trailing -e 100 --timerange 20210101-20210316`

**Comment by Rikj000** [comment]
I can already confirm that HyperOpting only `--spaces buy sell` works on my end.   
Further investigation is still needed, but I could see why perhaps buy/sell separately can't be HyperOpted due to MGMs way of initializing things

**Comment by Rikj000** [comment]
Further investigation is still needed, I'm starting to think that it might be due to how MGM initializes stuff on the 1st HyperOpt Run.
There it just uses the middle of the spaces to start out with. And that might be quite a sucky initial setup, so if all spaces are not optimized it might lead to no results found? :thinking: 
My next tests will be a 2nd HyperOpt Run based on partial results (I'll only leave buy & sell params in my `mgm-config-hyperopt.json`. That way the strategy should definitely buy trades again, and thus like that we maybe also will be able to hyperopt the other spaces separately again?

**Example of what I mean with initializes in the middle of the spaces:**
![MGM-MiddleOfSearchSpaces](https://user-images.githubusercontent.com/24852597/121565321-e4fa6c00-ca0b-11eb-936b-800f150f33ba.png)

**Comment by Rikj000** [comment]
> Further investigation is still needed, I'm starting to think that it might be due to how MGM initializes stuff on the 1st HyperOpt Run.
> My next tests will be a 2nd HyperOpt Run based on partial results (I'll only leave `buy` params in my `mgm-config-hyperopt.json`. That way the strategy should definitely buy trades again, and thus like that we maybe also will be able to hyperopt the other spaces separately again?

There where indeed bugs with loading in separately, I got an uncommitted "bugfix" for this but still testing all the spaces for it, so far confirmed working:
- `--spaces roi`

:arrow_up: I'll update this when I got more results but still testing through all the spaces

**Comment by Rikj000** [comment]
All individual spaces should work again now on the `development` branch :partying_face: 
Keep in mind that some results do need to be present before certain spaces will start providing valid outputs
