### ISSUE TITLE
Hyperopt is ignoring trailing_stop_positive_offset_max_value

### ISSUE THREAD

**Issue by 3ylo** [Rikj000/MoniGoMani#53]
The hyperopt is ignoring the "trailing_stop_positive_offset_max_value": 0.028 and opting for values higher than the configured max_value.

"trailing_stop_positive_min_value": 0.01,
"trailing_stop_positive_max_value": 0.021,
"trailing_stop_positive_offset_min_value": 0.011,
"trailing_stop_positive_offset_max_value": 0.028,

# Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.014
    trailing_stop_positive_offset = 0.038
    trailing_only_offset_is_reached = True

**Comment by Rikj000** [comment]
On my end the results also appear off! :open_mouth:   
Appears to only occur for the `trailing_stop_positive_offset` value.   

### mgm-config.json - `stoploss_spaces` section:   
```json
{
    "stoploss_min_value": -0.02,
    "stoploss_max_value": -0.35,
    "trailing_stop_positive_min_value": 0.01,
    "trailing_stop_positive_max_value": 0.35,
    "trailing_stop_positive_offset_min_value": 0.011,
    "trailing_stop_positive_offset_max_value": 0.1
}
```
### Results found:   
```python
# Stoploss:
stoploss = -0.288

# Trailing stop:
trailing_stop = True
trailing_stop_positive = 0.253
trailing_stop_positive_offset = 0.326
trailing_only_offset_is_reached = True
```

**Comment by raftersvk** [comment]
coud it be just the position of the default values interfering with the mgm-comfig.json
on my local setup I have commented that part ant it works perfectly so far :
![image](https://user-images.githubusercontent.com/48151933/121079284-3c18fa80-c7da-11eb-8eed-d0e660c36d4c.png)

**Comment by Rikj000** [comment]
> coud it be just the position of the default values interfering with the mgm-comfig.json
> on my local setup I have commented that part ant it works perfectly so far :

Truly nice findings @raftersvk! :clap: So a little more exact, you commented out lines 118 - 125? :eyes: 
I would leave the `buy_params` and `sell_params` lines (119 - 120) there though, to prevent issues when loading in `'mgm-config-hyperopt.json` during the second HyperOpt Run.   

Currently I'm still working on the Docs & HyperOpting protections, would be nice if you could provide some of the fixed results in the meantime to speed things up :slightly_smiling_face:

**Comment by raftersvk** [comment]
indeed I have left the buy / sell_params for the strat to work properly.

**Comment by Rikj000** [comment]
So when taking a closer look at the documentation I wondered if there even was a bug at all
![MGM-Custom-Stoploss](https://user-images.githubusercontent.com/24852597/121424504-ed499d00-c960-11eb-8428-6ac449838779.png)
And after diving in Freqtrades source code I can confirm all looks to be in order :tada:
![Freqtrade-Source-Stoploss](https://user-images.githubusercontent.com/24852597/121424518-f175ba80-c960-11eb-9ea2-55ff0d51ebbb.png)
