### ISSUE TITLE
Update from custom `Rikj000/Freqtrade/moni-go-mani/v0.11.0` to official `freqtrade/freqtrade/develop`

### ISSUE THREAD

**Issue by ferater** [Rikj000/MoniGoMani#59]
**Error:** ` 'No module named 'freqtrade.state''`

**Solution:** `from freqtrade.enums import RunMode` should be used instead of `from freqtrade.state import RunMode`

**Comment by Rikj000** [comment]
Nice thanks for making this an easy fix! :mechanical_arm:

**Comment by Rikj000** [comment]
Please stick to the custom Freqtrade version mentioned [here](https://github.com/Rikj000/MoniGoMani/issues/40#issuecomment-861299610) until this issue is closed!

**Comment by rodrigogs** [comment]
My hero!

I was stuck with that for a while hahaha

**Comment by rodrigogs** [comment]
So, it means that we can just use the original freqtrade from now on?

**Comment by Rikj000** [comment]
> So, it means that we can just use the original freqtrade from now on?

Absolutely! :tada:
