### ISSUE TITLE
retrieve a current Binance-USDT-All-Tradable-StaticPairList.json file & "isMarginTradingAllowed==True

### ISSUE THREAD

**Issue by pascal00d** [Rikj000/MoniGoMani#63]
Hello,

To retrieve a current Binance-USDT-All-Tradable-StaticPairList.json file, in Binance-Retrieve-All-Tradable-StaticPairList.py you check that "isMarginTradingAllowed==True".

With "isMarginTradingAllowed==True" => 131 pairs
Without "isMarginTradingAllowed==True" => 233 pairs

What is the reason to check that "isMarginTradingAllowed==True" ?

**Comment by Rikj000** [comment]
> Hello,
> 
> To retrieve a current Binance-USDT-All-Tradable-StaticPairList.json file, in Binance-Retrieve-All-Tradable-StaticPairList.py you check that "isMarginTradingAllowed==True".
> 
> With "isMarginTradingAllowed==True" => 131 pairs
> Without "isMarginTradingAllowed==True" => 233 pairs
> 
> What is the reason to check that "isMarginTradingAllowed==True" ?

Good question, @PoCk3T is the creator of this tool, maybe he can elaborate this.   
For now I'll remove it upon my next commits pushed since indeed this tool's current purpose is mostly to pull All-Tradable pairs!

**Comment by Rikj000** [comment]
Margin trade limitation disabled in commit: https://github.com/Rikj000/MoniGoMani/commit/499f4d5cc986a480b1d721310e57a3cf1f877aad

**Comment by pascal00d** [comment]
Thanks for your work !

**Comment by PoCk3T** [comment]
As far as I remember, some of the pairs that shows up if you remove "isMarginTradingAllowed==True" are simply not traded anymore

**Comment by 3ylo** [comment]
> As far as I remember, some of the pairs that shows up if you remove "isMarginTradingAllowed==True" are simply not traded anymore

I wonder if it is related to leveraged pairs used on margin trading.If that's the case I believe they will be blacklisted because of the high risk.
https://academy.binance.com/en/articles/what-is-margin-trading
https://academy.binance.com/en/articles/a-beginners-guide-to-binance-leveraged-tokens-blvt

**Comment by Rikj000** [comment]
> As far as I remember, some of the pairs that shows up if you remove "isMarginTradingAllowed==True" are simply not traded anymore

Can't find much on the matter besides this: https://dev.binance.vision/t/ismargintradingallowed-the-same-as-shortable/2274
It's function is clear though, to only leave pairs in the list that are margin trade-able.

But if you say that pairs would be added that are not traded anymore, then do you mean not available anymore?
Or do you mean still available but quite unpopular?

**Comment by PoCk3T** [comment]
With "isMarginTradingAllowed==True" => 131 pairs
Without "isMarginTradingAllowed==True" => 233 pairs
Delta = 102 pairs

Very concretely, if we remove "isMarginTradingAllowed==True", get a list of pairs, and try to download OHCLV data for these pairs, Binance will tell you 102 of these pairs don't exist and the freqtrade download-data tool will ask you to remove these pairs from your list.

Additionally, pick one of these 102 pairs, and as far as I've seen myself, you will see these are old shitcoins

**Comment by Rikj000** [comment]
> Very concretely, if we remove "isMarginTradingAllowed==True", get a list of pairs, and try to download OHCLV data for these pairs, Binance will tell you 102 of these pairs don't exist and the freqtrade download-data tool will ask you to remove these pairs from your list.

Alright that settles it :smile: `and d['isMarginTradingAllowed'] is True` shall remain uncommented :slightly_smiling_face:

**Comment by Rikj000** [comment]
Re-enabled in commit: https://github.com/Rikj000/MoniGoMani/commit/f726c79f9ed04df3789165ceab9b1667c6cbacc3
