### ISSUE TITLE
hyperopt_tools.py: print_epoch_details has been changed to show_epoch_details

### ISSUE THREAD

**Issue by andif888** [Rikj000/MoniGoMani#64]
`print_epoch_details(...)` has been changed to `show_epoch_details(...)` in [hyperopt_tools.py](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/hyperopt_tools.py)
See https://github.com/freqtrade/freqtrade/commit/d54ee0eb040b975a0e71cb6ccc106babd2f55d12
I try to send a PR.

**Comment by rvasilev** [comment]
That's sort of breaking change, so dev branch of MGM will be incompatible with current stable freqtrade?

**Comment by andif888** [comment]
dev branch of MGM is now incompatible with freqtrade's develop branch. 
stable freqtrade branch has not changed yet. 

[Dockerfile.MoniGoMani](https://github.com/Rikj000/MoniGoMani/blob/development/docker/Dockerfile.MoniGoMani) uses `FROM freqtradeorg/freqtrade:develop` and copies: 
```
COPY ./user_data/mgm_tools/hyperopt_tools.py freqtrade/optimize/hyperopt_tools.py
``` 
which makes it incompatible.

**Comment by rvasilev** [comment]
What means MGM v0.12 will not release until next stable freqtrade (2021.06 I suppose). 

Looks like MGM documentation should reflect compatible freqtrade  version. 

As a nasty option - new MGM branch based on stable freqtrade (say, MGM-next) to back port non-breaking changes/features from MGM development.

**Comment by Rikj000** [comment]
The plan is soon to move back to the official Freqtrade `development` branch (when `v0.12.0` comes out) where these fixes should not be needed anymore

**Comment by Rikj000** [comment]
> dev branch of MGM is now incompatible with freqtrade's develop branch.
> stable freqtrade branch has not changed yet.
> 
> [Dockerfile.MoniGoMani](https://github.com/Rikj000/MoniGoMani/blob/development/docker/Dockerfile.MoniGoMani) uses `FROM freqtradeorg/freqtrade:develop` and copies:
> 
> ```
> COPY ./user_data/mgm_tools/hyperopt_tools.py freqtrade/optimize/hyperopt_tools.py
> ```
> 
> which makes it incompatible.
