### ISSUE TITLE
Getting exception while running through Docker

### ISSUE THREAD

**Issue by kaggrwal** [Rikj000/MoniGoMani#68]
I was trying to run the bot using the quickstart guide via docker image. I got the following exception, please let me know how to resolve it ?

`INFO - Starting freqtrade docker-0af9bcef
Freqtrade-MoniGoMani | 2021-06-17 00:04:58,961 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/MoniGoManiHyperStrategy.py due to 'No module named 'freqtrade.state''
Freqtrade-MoniGoMani | 2021-06-17 00:04:58,961 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'MoniGoManiHyperStrategy'. This class does not exist or contains Python code errors.
Freqtrade-MoniGoMani | 2021-06-17 00:04:58,961 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Freqtrade-MoniGoMani | Traceback (most recent call last):
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
Freqtrade-MoniGoMani |     worker = Worker(args)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
Freqtrade-MoniGoMani |     self._init(False)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
Freqtrade-MoniGoMani |     self.freqtrade = FreqtradeBot(self._config)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
Freqtrade-MoniGoMani |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
Freqtrade-MoniGoMani |     strategy: IStrategy = StrategyResolver._load_strategy(
Freqtrade-MoniGoMani |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 205, in _load_strategy
Freqtrade-MoniGoMani |     raise OperationalException(
Freqtrade-MoniGoMani | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'MoniGoManiHyperStrategy'. This class does not exist or contains Python code errors.
`

**Comment by denvers** [comment]
Try this fork until the PR gets merged into freqtrade:

`$ git clone -b hyperopt-show-include-non-optimized-in-json https://github.com/Rikj000/Freqtrade.git`

**Comment by Rikj000** [comment]
A little more patience and check: https://github.com/Rikj000/MoniGoMani/issues/64#issuecomment-860288297

**Comment by jegb** [comment]
I am still getting this error, I am on stable 2021.8

"freqtrade.commands.trade_commands - ERROR - Fatal exception!"

What is the workaround?

**Comment by Rikj000** [comment]
> I am still getting this error, I am on stable 2021.8

Your Freqtrade version is too new, please install the latest supported (mentioned in development readme & auto installed by mgm-hurry) as a source install.

**Comment by jegb** [comment]
okei, went from the beginning using the script which was very useful. I got
it working once, but somehow after a while on next hyperopt run was asking
for the json file (related to the hyperopt). I will gather more information
and post on discord.
