### ISSUE TITLE
Different machines = different profit performance?

### ISSUE THREAD

**Issue by rodrigogs** [Rikj000/MoniGoMani#77]
I'm getting different backtesting results for the exact same(zipped>unzipped) repository directory in two different machines.

One is a regular machine, i7 gen 10 with 17gb ram. The other one is a pi 4 with 2 gb of ram.

The scenario is that in my i7 machine I make a good amount of profit in the backtestings. It's not the case when I run the exact same command, with the exact same downloaded data and both running on docker with the latest image... I actually lose money in my pi 4 hahahahaha

So the question is: does it make any sense? Do I need to run the trained strategy in the same machine that was used for training?

**Comment by Rikj000** [comment]
> So the question is: does it make any sense? Do I need to run the trained strategy in the same machine that was used for training?

Hmmm I would assume something just is different in the installations on both machines. A lot of factors come into play here (All software versions matter, MGM, Freqtrade and all their dependencies)
First thing I'd check is `freqtrade -V` on both machines, to confirm if indeed identical Freqtrade installations are present, it's easy to mismatch on Freqtrade's `develop` branch with Docker.
Then the CCXT version (printed in your log output when you HyperOpt)

**Comment by rodrigogs** [comment]
I'll test it as soon as I can

**Comment by kamontat** [comment]
You might take a look on shuffling / random seed as well.

**Comment by Rikj000** [comment]
> You might take a look on shuffling / random seed as well.

That's a good point! @rodrigogs make sure to run both tests with the same `--random-state`
https://www.freqtrade.io/en/latest/hyperopt/#reproducible-results
