### ISSUE TITLE
Build ema 200

### ISSUE THREAD

**Issue by paultodev** [Rikj000/MoniGoMani#80]
New to this but as I understood so far is that: in order for ema 200 indicator to populate one should wait more than 8 days.
My question is if there is a way to populate this from historical data?

**Comment by NecroJogn** [comment]
I believe this is already done by Freqtrade automatically. You should however have that historical data downloaded manually before running it dry/live.

**Comment by Rikj000** [comment]
> My question is if there is a way to populate this from historical data?

As @NecroJogn mentioned, Freqtrade does this automatically using it's `startup_candle_count`, you just need to make sure you have downloaded enough candle data for the startup candle period aswel, then HyperOpt will automatically add the extra data needed
