### ISSUE TITLE
Change the way to import Master*Strategy

### ISSUE THREAD

**Issue by rvasilev** [Rikj000/MoniGoMani#83]
Apparently it's just mine problem with failed module imports, but `MoniGoManiHyperStrategy` can import `Master` from the same directory without using dot notation.

Before:
https://github.com/Rikj000/MoniGoMani/blob/fef98cccf29577fe4396973a33af96bd611185e6/user_data/strategies/MoniGoManiHyperStrategy.py#L11

After:
```py
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))

from MasterMoniGoManiHyperStrategy import MasterMoniGoManiHyperStrategy
```

**Comment by Rikj000** [comment]
I'll be sure to check it out once I wrapped up my current unclogger improvement! :smile: 
If it all checks out on my end it can go in, however I had no such issues so far :open_mouth:
