### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by distatk** [Rikj000/MoniGoMani#95]
I got an error that say json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes after running the hyper opting in go-to command

freqtrade hyperopt -s MoniGoManiHyperStrategy -c ./user_data/mgm-config.json -c ./user_data/mgm-config-private.json --hyperopt-loss WinRatioAndProfitRatioLoss --spaces all -e 800 --timerange 20210101-20210316 --enable-protections
![215398928_1498409967183944_7992954481712727140_n](https://user-images.githubusercontent.com/86469208/125985246-14babd61-986f-4c6c-8bf8-e7ca40ed1c18.png)

**Comment by Rikj000** [comment]
Fixed by @distatk, the binance api key was in the wrong file
