### ISSUE TITLE
OpenAI integration

### ISSUE THREAD

**Issue by tinof** [Rikj000/MoniGoMani#98]
It would be interesting to see your work on Freqtrade combined with this OpenAI based hyperopt feature for Freqtrade: https://github.com/hugocen/freqtrade-gym

**Comment by Rikj000** [comment]
> It would be interesting to see your work on Freqtrade combined with this OpenAI based hyperopt feature for Freqtrade: https://github.com/hugocen/freqtrade-gym

Perhaps yes, however I'm currently so overloaded with work that I won't have time to check that or give it's implementation a try any time soon.
But feel free to report back to tell how it goes.

**Comment by Rikj000** [comment]
@tinof feel free to re-open once you feel like implementing this
